FROM postgres:17-alpine

# Optional: custom config
COPY initdb/ /docker-entrypoint-initdb.d

# Expose default port
EXPOSE 5432

# Use custom config (optional)
CMD ["postgres", "-c", "config_file=/etc/postgresql/postgresql.conf"]

